version: '3.8'

services:
  app:
    build:
      context: .
      target: builder  
    container_name: express_typescript_app
    restart: unless-stopped
    env_file:
      - ./.env.development
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DB_HOST=db
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - /app/node_modules 
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    env_file:
      - ./.env.development
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  db_data:
