version: '3.8'

services:
  app:
    build: .
    container_name: express_typescript_app
    restart: unless-stopped
    env_file:
      - ./.env.production # <-- Memuat semua variabel dari file .env
    ports:
      - "${PORT}:${PORT}" # <-- Menggunakan variabel PORT dari .env
    environment:
      - DB_HOST=db # <-- MENIMPA DB_HOST dari .env menjadi 'db'
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
    command: npm run dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    env_file:
      - ./.env.production # <-- Memuat variabel dari .env juga
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: